apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: VSphereMachine
metadata:
  name: vsphere-controlplane-9
spec:
  datacenter: "dc1"
  network:
    devices:
    - networkName: "network_test"
      dhcp4: false
      dhcp6: false
      ipAddrs:
      - "notinfoblox"
      - "infoblox:somenetview:somednsview:somecidr"
  numCPUs: 3
  memoryMiB: 40
  diskGiB: 40
  template: "t1"
